blueiris:
  #hostname / ip of BlueIris WebServer
  host: !secret blueiris_host
  #port of BlueIris WebServer
  port: !secret blueiris_port
  #Optional - will create switch if defined
  profile:
    #armed profile number
    armed: !secret blueiris_profile_armed
    #unarmed profile number
    unarmed: !secret blueiris_profile_unarmed
  #Username
  username: !secret blueiris_api_username
  #Password
  password: !secret blueiris_api_password
  #Optional - will allow creating binary sensors
  mqtt:
    #Watchdog MQTT Topic
    watchdog: BlueIris/[camera_id]/Connectivity
    #Motion MQTT Topic
    motion: BlueIris/[camera_id]/Motion
  #List of camera object
  camera: 
      #name of the camera for display
    - name: 'Kitchen Camera'
      #BlueIris camera's short name
      id: Kitchen
      #Room name (adds as attribute)
      room: Ground Floor

camera:
    #creates cameras according to the camera defined in the platform
  - platform: blueiris
 
binary_sensor:
    #creates binary sensors according per camera defined in the platform with the topics defined
  - platform: blueiris

switch:
    #creates switch to arm and disarm BlueIris (available only when profile provided)
  - platform: blueiris